apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo-container
          image: odoo
          env:
            - name: HOST
              value: "postgres-service"
          ports:
            - containerPort: 8069
              name: "odoo-http"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  ports:
  - port: 8069
    targetPort: odoo-http
  selector:
    app: odoo
