apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
    spec:
      volumes:
        - name: postgres-persistent
          persistentVolumeClaim:
            claimName: postgres-claim
      containers:
        - name: postgres-container
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "odoo"
            - name: POSTGRES_PASSWORD
              value: "odoo"
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              name: "pg-server"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-persistent
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: pg-server
  selector:
    app: odoo-postgres
