apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
spec:
  storageClassName: rook-ceph-block
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: odoo-postgres
  labels:
    app: odoo-postgres
spec:
  nodeName: node-2
  volumes:
    - name: postgres-persistent
      persistentVolumeClaim:
        claimName: postgres-claim
  containers:
    - name: postgres-container
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_PASSWORD
          value: "odoo"
        - name: POSTGRES_DB
          value: postgres
      ports:
        - containerPort: 5432
          name: "pg-server"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-persistent
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: pg-server
  selector:
    app: odoo-postgres