---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatbot-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/cb"
---